name: Java CI with Gradle

on:
  push:
    branches: [ ufarooq ]
  pull_request:
    branches: [ ufarooq ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x LiveDroid/gradlew
    - name: Build Analyzer with Gradle
      run: cd LiveDroid && ./gradlew :analyzer:shadowJar
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: LiveDroid/analyzer/build/libs
    - name: Build Patcher with Gradle
      run: cd LiveDroid && ./gradlew :patcher:shadowJar
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: LiveDroid/patcher/build/libs
    - name: Build the Plugin with Gradle
      run: cd LiveDroid && ./gradlew :plugin:buildPlugin
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: LiveDroid/plugin/build/distributions/
